### ISSUE TITLE
一键登录AppID Secret解析失败，错误码600017

### ISSUE THREAD

**Issue by a843647878** [ManInTheWind/flutter_ali_auth#33]
### Version

0.7.0

### Platforms

Android

### Device Model

红米K50（Android 13）

### flutter info

```sh
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [版本 10.0.22000.120], locale zh-CN)
    • Flutter version 3.3.0 on channel stable at D:\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (1 year, 4 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\SDK
    • Platform android-34, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • 22041211AC (mobile) • DM6TAYOFFEBUGU5X • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [版本 10.0.22000.120]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 120.0.6099.216
```

### How to reproduce?

必现，Android和ios码都填写确认了，Android也取消了混淆

### Logs

```sh
E/AuthSDK ( 5269): 	at com.fluttercandies.flutter_ali_auth.FlutterAliAuthPlugin.onMethodCall(FlutterAliAuthPlugin.java:64)
E/AuthSDK ( 5269): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AuthSDK ( 5269): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AuthSDK ( 5269): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AuthSDK ( 5269): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AuthSDK ( 5269): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AuthSDK ( 5269): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AuthSDK ( 5269): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AuthSDK ( 5269): 	at android.os.Looper.loop(Looper.java:299)
E/AuthSDK ( 5269): 	at android.app.ActivityThread.main(ActivityThread.java:8136)
E/AuthSDK ( 5269): 	at java.lang.reflect.Method.invoke(Native Method)
E/AuthSDK ( 5269): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AuthSDK ( 5269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)


checkEnvAvailable errorCode = 600017; errorMsg = AppID Secret解析失败
D/AuthClient( 5269): initSdk onTokenFailed: {"carrierFailedResultData":"","code":"600017","msg":"AppID Secret解析失败","requestCode":0,"requestId":"931165e6-8551-4aa4-aad1-e2dda0ad2ef1","vendorName":"cm_zyhl"}
```

### Contact

843647878@qq.com

**Comment by ethan-202285** [comment]
参考这个成功了。https://github.com/fluttercandies/flutter_ali_auth/issues/7

**Comment by AKA-LinCoder** [comment]
想问下解决了么，debug模式是正常的，但是release模式下一直AppID Secret解析失败，也取消了混淆

**Comment by a843647878** [comment]
解决了&nbsp; &nbsp;问题是Key弄错了&nbsp; &nbsp;阿里有2套这个东西&nbsp; 一套是融合认证&nbsp; &nbsp;一套是号码认证&nbsp; 之前做Android端用的是融合&nbsp; 导致开发flutter的时候key对应不上&nbsp; &nbsp;换一套就行了


CU
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_ali_auth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月11日(星期五) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluttercandies/flutter_ali_auth] 一键登录AppID Secret解析失败，错误码600017 (Issue #33)





 
想问下解决了么，debug模式是正常的，但是release模式下一直AppID Secret解析失败，也取消了混淆

**Comment by AKA-LinCoder** [comment]
nfg
