### ISSUE TITLE
[Bug report] 联通手机号报错 {"resultCode":"600012","msg":"应用无效","requestId":"67316cb2-8131-488b-b175-9530664ffd95"}

### ISSUE THREAD

**Issue by shichunlei** [ManInTheWind/flutter_ali_auth#37]
### Version

0.7.0

### Platforms

dart

### Device Model

小米 11 android 13

### flutter info

```sh
[✓] Flutter (Channel stable, 3.16.8, on macOS 13.2 22D49 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
```

### How to reproduce?

双卡手机，一开始使用电信联网，一切正常，然后流量切换到联通手机号包下面的错误{"resultCode":"600012","msg":"应用无效","requestId":"67316cb2-8131-488b-b175-9530664ffd95"}

一开始流量使用联通手机号也是同样的问题

### Logs

```sh
W/System.err(30581): org.json.JSONException: End of input at character 0 of 
W/System.err(30581): 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
W/System.err(30581): 	at org.json.JSONTokener.nextValue(JSONTokener.java:101)
W/System.err(30581): 	at org.json.JSONObject.<init>(JSONObject.java:168)
W/System.err(30581): 	at org.json.JSONObject.<init>(JSONObject.java:185)
W/System.err(30581): 	at com.nirvana.tools.jsoner.JSONUtils.fromJson(Unknown Source:138)
W/System.err(30581): 	at com.mobile.auth.gatewayauth.model.cucctoken.CUCCTokenRB.fromJson(Unknown Source:1)
W/System.err(30581): 	at com.nirvana.tools.jsoner.JSONUtils.fromJson(Unknown Source:11)
W/System.err(30581): 	at com.mobile.auth.gatewayauth.model.cucctoken.CUCCTokenRB.fromJson(Unknown Source:17)
W/System.err(30581): 	at com.mobile.auth.u.a$1.a(Unknown Source:50)
W/System.err(30581): 	at com.mobile.auth.ab.b.a(Unknown Source:45)
W/System.err(30581): 	at com.mobile.auth.ab.a$2.a(Unknown Source:127)
W/System.err(30581): 	at com.mobile.auth.ab.a$4.run(Unknown Source:40)
W/System.err(30581): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
W/System.err(30581): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/System.err(30581): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err(30581): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err(30581): 	at java.lang.Thread.run(Thread.java:1012)
E/AuthSDK (30581): justGetLoginPhone failed!{"a":"600012","b":"应用无效","c":"{\"resultCode\":102,\"resultMsg\":\"应用无效\",\"resultData\":\"\",\"traceId\":\"\",\"operatorType\":\"CU\"}","d":"{\"msg\":\"应用无效\",\"code\":\"102\"}","e":false,"f":0}
W/AuthClient(30581): 获取Token失败:{"carrierFailedResultData":"{\"resultCode\":102,\"resultMsg\":\"应用无效\",\"resultData\":\"\",\"traceId\":\"\",\"operatorType\":\"CU\"}","code":"600012","msg":"应用无效","requestCode":0,"requestId":"67316cb2-8131-488b-b175-9530664ffd95","vendorName":"cu_xw"} ,DecoyMaskActivity.isRunning:com.fluttercandies.flutter_ali_auth.mask.DecoyMaskActivity@6845a99
I/AuthClient(30581): tokenRet:TokenRet{vendorName='cu_xw', code='600012', msg='应用无效', carrierFailedResultData={"resultCode":102,"resultMsg":"应用无效","resultData":"","traceId":"","operatorType":"CU"}', requestId=67316cb2-8131-488b-b175-9530664ffd95', requestCode=0, token='null'}
I/flutter (30581): responseModel:{"resultCode":"600012","msg":"应用无效","requestId":"67316cb2-8131-488b-b175-9530664ffd95"}
W/hanyu.hanyu_bct(30581): Attempt to remove non-JNI local reference, dumping thread
I/flutter (30581): [600012] 预取号失败
I/flutter (30581): {"resultCode":"600012","msg":"应用无效","requestId":"67316cb2-8131-488b-b175-9530664ffd95"}
D/DecorView[](30581): onWindowFocusChanged hasWindowFocus false
```

### Example code (optional)

```Dart
AliAuthClient.initSdk(authConfig:AuthConfig(
      iosSdk:
          "",
      androidSdk:
          "",
      enableLog: false,
      authUIStyle: AuthUIStyle.fullScreen,
      authUIConfig: FullScreenUIConfig(navConfig: NavConfig(navColor: Colors.cyan.toHex()))));


await AliAuthClient.login();
```

**Comment by DaYang816** [comment]
#34
