### ISSUE TITLE
fastjson release 闪退

### ISSUE THREAD

**Issue by herowws** [ManInTheWind/flutter_ali_auth#5]

**Comment by ManInTheWind** [comment]
报错信息呢？？？

**Comment by herowws** [comment]
![H7J8$TKQW0I3L(_C)6 1XT](https://user-images.githubusercontent.com/41428542/211726543-c7bbe64a-0f12-4e51-98ee-0e17326c75e7.jpg)

**Comment by herowws** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/fastjson2/util/JDKUtils$$ExternalSyntheticLambda0;
      	at com.alibaba.fastjson2.util.JDKUtils.<clinit>(JDKUtils.java:44)
      	at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:158)
      	at com.alibaba.fastjson2.JSON$-CC.toJSON(JSON.java:2581)
      	at com.alibaba.fastjson2.JSON$-CC.toJSON(JSON.java:2563)
      	at com.fluttercandies.flutter_ali_auth.model.AuthModel.Builder(AuthModel.java:20)
      	at com.fluttercandies.flutter_ali_auth.AuthClient.initSdk(AuthClient.java:73)
      	at com.fluttercandies.flutter_ali_auth.FlutterAliAuthPlugin.onMethodCall(FlutterAliAuthPlugin.java:94)
      	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
      	at android.os.Handler.handleCallback(Handler.java:742)

**Comment by ManInTheWind** [comment]
我晚点看看

**Comment by herowws** [comment]
waiting

**Comment by herowws** [comment]
改成fastjson1 之后不崩溃

**Comment by ManInTheWind** [comment]
0.3.0已更新
